services:
  - type: web
    name: calendar-api
    runtime: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: NODE_ENV
        value: production
